/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCheckbox: typeof import('./src/components/base/base-checkbox.vue')['default']
    BaseImg: typeof import('./src/components/base/base-img.vue')['default']
    BaseImgCard: typeof import('./src/components/base/base-img-card.vue')['default']
    BaseVirtualScrollbar: typeof import('./src/components/base/base-virtual-scrollbar.vue')['default']
    HoverButton: typeof import('./src/components/hover-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarButtonGroup: typeof import('@varlet/ui')['_ButtonGroupComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarFab: typeof import('@varlet/ui')['_FabComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    WaterfallList: typeof import('./src/components/base/waterfall-list.vue')['default']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
