/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCheckbox: typeof import('./../src/components/base/base-checkbox.vue')['default']
    BaseImg: typeof import('./../src/components/base/base-img.vue')['default']
    BaseImgCard: typeof import('./../src/components/base/base-img-card.vue')['default']
    BaseVirtualScrollbar: typeof import('./../src/components/base/base-virtual-scrollbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTree: typeof import('element-plus/es')['ElTree']
    IAntDesignCheckCircleFilled: typeof import('~icons/ant-design/check-circle-filled')['default']
    IAntDesignCloseCircleFilled: typeof import('~icons/ant-design/close-circle-filled')['default']
    IAntDesignEditOutlined: typeof import('~icons/ant-design/edit-outlined')['default']
    IAntDesignMenuOutlined: typeof import('~icons/ant-design/menu-outlined')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IMaterialSymbolsArrowDropDownRounded: typeof import('~icons/material-symbols/arrow-drop-down-rounded')['default']
    IMaterialSymbolsBoxEdit: typeof import('~icons/material-symbols/box-edit')['default']
    IMaterialSymbolsCheckBoxOutlineBlank: typeof import('~icons/material-symbols/check-box-outline-blank')['default']
    IMaterialSymbolsCheckBoxRounded: typeof import('~icons/material-symbols/check-box-rounded')['default']
    IMaterialSymbolsDelete: typeof import('~icons/material-symbols/delete')['default']
    IMaterialSymbolsDownload: typeof import('~icons/material-symbols/download')['default']
    IMaterialSymbolsGalleryThumbnail: typeof import('~icons/material-symbols/gallery-thumbnail')['default']
    IMaterialSymbolsLocationOnOutline: typeof import('~icons/material-symbols/location-on-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarButtonGroup: typeof import('@varlet/ui')['_ButtonGroupComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarFab: typeof import('@varlet/ui')['_FabComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    WaterfallList: typeof import('./../src/components/base/waterfall-list.vue')['default']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
